<?php

/**
 * @file createAPageWithTemplate.module.
 */

/**
 * Implementation of hook_menu()
 */
function createAPageWithTemplate_menu() {
  $items['aNewPage'] = array(
    'title' => t('A New Page for Testing'),
    'page callback' => 'a_new_page_callback',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => 5,
  );

	return $items;
}

/**
 * Page callback: displaying a page with php template
 *  
 * @see createAPageWithTemplate_menu()
 */
function a_new_page_callback(){
  global $user;
  $build = array();

  $query = db_select('node', 'n')->extend('PagerDefault');
  $nids = $query
    ->fields('n', array('nid', 'sticky', 'created'))
    ->condition('type', 'blog')
    ->condition('status', 1)
    ->orderBy('sticky', 'DESC')
    ->orderBy('created', 'DESC')
    ->limit(variable_get('default_nodes_main', 10))
    ->addTag('node_access')
    ->execute()
    ->fetchCol();

  if (!empty($nids)) {
    $nodes = node_load_multiple($nids);
    $build += node_view_multiple($nodes);
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
  }
  else {
    drupal_set_message(t('No blog entries have been created.'));
  }

	return $build;
}
